
name: Flutter

on:  #events (push and pull_request)
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:   #here we specify the jobs - We could have multiple jobs
  build:  #name it something meaningful 
    runs-on: ubuntu-latest   #runner: select a machine to use

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
      # - run: ls build/app/outputs/bundle/release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_TOKEN}}
          groups: sparrow_team
          file: build/app/outputs/flutter-apk/app-debug.apk  